class CfgFunctions {
    class UKSF_PRC163 {
        tag = "UKSF_PRC163";
        class Radio {
            file = "\UKSF_PRC163\functions";
            class registerPresets {preInit = 1;};
            class registerKeybinds {preInit = 1;};
            class registerSettings {preInit = 1;};
            class registerInteractions {postInit = 1;};
            class initializeState {};
            class initializeBatteryState {};
            class monitorRadios {postInit = 1;};
            class getInteractionChildren {};
            class isPairHealthy {};
            class resolvePair {};
            class getTargetRadio {};
            class getBatterySlot {};
            class getBatteryRecord {};
            class getBatteryRecords {};
            class applyBatteryRecords {};
            class hasUsableBattery {};
            class drainBattery {};
            class replaceBattery {};
            class saveBatteryRecords {};
            class serverSaveBatteryRecords {};
            class serverLoadBatteryRecords {};
            class receiveBatteryRecords {};
            class getDisplayState {};
            class getHMIState {};
            class handleHMIInput {};
            class setVolume {};
            class getVolume {};
            class setSpatial {};
            class getSpatial {};
            class setOnOffState {};
            class setTxPower {};
            class getTxPower {};
            class updateDialog {};
            class openGui {};
            class closeGui {};
            class selectLine {};
            class setLineChannel {};
            class cycleChannel {};
            class dualWatchAvailability {};
            class handleMultipleTransmissions {};
            class handlePTTDown {};
            class handlePTTUp {};
            class toggleDualWatch {};
            class notifyStatus {};
        };
    };
};